{% set name = "azure-mgmt-cosmosdb" %}
{% set version = "9.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-mgmt-cosmosdb-{{ version }}.tar.gz
  sha256: cabb821cd446b09e73d24c31c287a60fcc3623488f1ffa9335c692267e79c341

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - isodate <1.0.0,>=0.6.1
    - azure-common >=1.1,<2
    - azure-mgmt-core >=1.3.2,<2.0.0

test:
  imports:
    - azure.mgmt.cosmosdb
    - azure.mgmt.cosmosdb.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Cosmos DB Management Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
