{% set name = "azure-mgmt-cosmosdb" %}
{% set version = "9.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 667c7d8a8f542b0e7972e63274af536ad985187e24a6cc2e3c8eef35560881fc

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - isodate <1.0.0,>=0.6.1
    - azure-common >=1.1,<2
    - azure-mgmt-core >=1.3.2,<2.0.0

test:
  imports:
    - azure.mgmt.cosmosdb
    - azure.mgmt.cosmosdb.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Cosmos DB Management Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
